*IMPORTANT: In this compendium, we will assume that you have knowledge of basic python programming and physics at the Bachelor level.*
# Numpy
NumPy (Numerical Python), is the foundational package for scientific computting in Python. It has a lot of uses beyond the fast array-processing capabilities that NumPy adds to Python. Such as:
<img src=https://miro.medium.com/max/724/1*6uZdO0mDuK5lDXZGgoVtLQ.jpeg>

## Index
* [Installation](#installation)
* [Import](#import)
* [Basic](#basic)
    * [Create arrays](#create)
    * [Slicing & indexes](#sli)
    * [Reshaping Array](#resha)
* [Mathematical operations](#mat)
    * [Arithmetic operations](#arit)
    * [Trigonometric functions](#tri)
    * [Hyperbolic functions](#hyp)
    * [Statistical operations](#stat)
    * [Other functions](#other)
* [Bitwise operators](#bit)
* [Copying & viewing arrays](#copy)
* [Stacking](#stack)
* [Matrix operations](#matrix)
* [Linear algebra](#linear)
* [Getting data in/out](#get)


## Installing <a class="anchor" id="installation"></a>
If you already have Python, you can install it with: **conda install numpy** or **pip install numpy**.

## Import <a class="import" id="import"></a>
You have to import Numpy in your Python code, to access NumPy and its functions.

In [109]:
import numpy as np

In [110]:
import matplotlib.pylab as plt
from numpy import random

# 1 - Basic <a class="basic" id="bssic"></a>
## 1.01 Create arrays <a class="create" id="create"></a>
You can build 3 types of arrays: 1D arrays, 2D arrays, ndarrays.
### The basic for 1D arrays
It need at least two inputs, start and stop.

***np.arange*** will create arrays with regularly incrementing values.

In [9]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [8]:
np.arange(10,15,0.5)#np.arange(start,stop,step)

array([10. , 10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5])

***np.linspace*** will create arrays with a specified number of elements, and spaced equally between the specified beginning and end values.

In [12]:
np.linspace(1,2,5) #np.linspace(start,end,how many)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

#### The basic for nD arrays
***np.eye(n, m)*** defines a identity matrix. The elements where i=j (row index and column index are equal) are 1 and the rest are 0, as such:

In [16]:
np.eye(4,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

***np.diag*** define an array with given values along the diagonal or if given a 2D array returns a 1D array that is only the diagonal elements.

In [17]:
np.diag([2,4,6])

array([[2, 0, 0],
       [0, 4, 0],
       [0, 0, 6]])

***np.zeros*** will return a new array of given shape and type, filled with zeros

In [17]:
np.zeros((3,3)) #numpy.zeros(shape, dtype=float, order='C', *, like=None)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

***np.ones*** will create an array filled with 1 values.

In [10]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

Yo can also create a multidimensional list and then make a numpy array with this one.

In [5]:
m_list=[[1,2,3],[4,5,6],[7,8,9]]

In [6]:
m_list

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(m_list)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

To generate random matrices,

In [22]:
np.random.randint(2,20,5) #np.random.randint(minimum,maximun,how many) 

array([19,  2, 13, 13,  2])

In [23]:
np.random.randint(2,20,size=(2,4)) #np.random.randint(minimum,maximun,size=()) 

array([[ 9, 12,  3, 19],
       [ 9,  8, 18,  2]])

### 1.012 Slicing & indexes <a class="sli" id="sli"></a>
To get the size of an array, you have to add .size after the arrays name. For example,

In [15]:
array1=np.ones((2,3))
array2=np.array(m_list)

print(array1.size, array2.size)

6 9


Yo can also **get the data type** for the array.

In [16]:
array1.dtype

dtype('float64')

To **change values of specfific indexes**:

In [26]:
array2[0,0]=2 # Change the upper left hand corner value to 2

In [27]:
array2.itemset((0,1),1)

In [28]:
array2

array([[2, 1, 3],
       [4, 5, 6],
       [7, 8, 9]])

To get the **shape** of arrays:

In [29]:
array2.shape

(3, 3)

You can also get specifics values:

In [35]:
array2[2,0] #array[row, column]

7

or this way

In [36]:
array2.item(2,0)

7

In [ ]:
Yo can get the second value from each row,

In [37]:
array2[:,1]

array([1, 5, 8])

Or the first value from each row,

In [39]:
array2[:,0]

array([2, 4, 7])

You can also flip a raise,

In [40]:
array2[::-1]

array([[7, 8, 9],
       [4, 5, 6],
       [2, 1, 3]])

To get **even values**:

In [42]:
evens = array2[array2%2==0]

In [43]:
evens

array([2, 4, 6, 8])

If you want to get values that are greater than five,

In [44]:
array2[array2 > 5]

array([6, 7, 8, 9])

If you want to get values that are greater than five and smaller than 10

In [45]:
array2[(array2 > 5) & (array2 < 10)]

array([6, 7, 8, 9])

You can also get the unique values of an array with **np.unique()**

In [47]:
np.unique(array2)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### 1.013 Reshaping Arrays <a class="resha" id="resha"></a>
If you have a multi-dimensional array an you want to reshape it into a nine-item single axis array:

In [48]:
array2.reshape((1,9))

array([[2, 1, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
You can also resize it

In [50]:
np.resize(array2, (2,5))

array([[2, 1, 3, 4, 5],
       [6, 7, 8, 9, 2]])

Note that because elements were missing to complete the matrix in which it was resized, the elements are repeated to fill the empty spaces.

To **tranpose the axis**:

In [52]:
array2.transpose()

array([[2, 4, 7],
       [1, 5, 8],
       [3, 6, 9]])

To **swap axis**:

In [58]:
array2.swapaxes(0,1)

array([[2, 4, 7],
       [1, 5, 8],
       [3, 6, 9]])

To **flatten the array**:

In [59]:
array2.flatten()

array([2, 1, 3, 4, 5, 6, 7, 8, 9])

To flatten **in column order**:

In [61]:
array2.flatten('F')

array([2, 4, 7, 1, 5, 8, 3, 6, 9])

To **sort the rows**:

In [63]:
array2.sort(axis=1)

In [64]:
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

*For more NumPy commands to create arrays*

https://numpy.org/doc/stable/reference/routines.array-creation.html#routines-array-creation
## 1.02 Mathematical operations <a class="mat" id="mat"></a>
### Arithmetic operations <a class="arit" id="arit"></a>
***np.add()*** 

For example: $$3+5=$$

In [3]:
np.add(3,5)

8

***np.subtract()*** 

For example: $$5-3=$$

In [3]:
np.subtract(5,3)

2

***np.multiply()***

For example: $$5*3=$$

In [4]:
np.multiply(5,3)

15

***np.divide()***

For example: $$\frac{6}{3}=$$

In [6]:
np.divide(6,3)

2.0

***np.prod(a)***: Return the product of array elements over a given axis.

In [21]:
np.prod([2,3])

6

***np.reciprocal()*** returns the reciprocal of argument, element-wise.

In [87]:
?

***np.power(a,b)*** treats elements in the first input array as base and returns it raised to the power of the corresponding element in the second input array.
$$a^b$$


In [78]:
np.power(3,2)

9

***np.mod()*** returns the remainder of division of the corresponding elements in the input array. 

In [8]:
np.mod(5,3)

2

#### Let's make an exercise, if we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.
#### Find the sum of all the multiples of 3 or 5 below 1000.

In [88]:
def Ex1(x):
    a=0
    for n in range(x):
        if (np.mod(n,3)==0 or np.mod(n,5)==0):
            a = np.add(n,a)
    return a

In [90]:
Ex1(10)

23

In [89]:
Ex1(1000) #This is the answer

233168

***np.real()*** returns the real part of the complex data type argument.

In [14]:
np.real(5+3j)

5.0

***np.imag()*** returns the imaginary part of the complex data type argument.

In [15]:
np.imag(5+3j)

3.0

***np.conj()*** returns the complex conjugate, which is obtained by changing the sign of the imaginary part.

In [16]:
np.conj(5+4j)

(5-4j)

***np.angle()*** returns the angle of the complex argument. The function has degree parameter. If true, the angle in the degree is returned, otherwise the angle is in radians.

In [18]:
np.angle(5+4j)

0.6747409422235526

### Trigonometric functions <a class="tri" id="tri"></a>

- ***np.sin(x)***: Trigonometric sine, element-wise.

- ***np.cos(x)***: Cosine element-wise.

- ***np.tan(x)***: Compute tangent element-wise.

- ***np.arcsin(x)***: Inverse sine, element-wise.

- ***np.arccos(x)***: Trigonometric inverse cosine, element-wise.

- ***np.arctan(x)***: Trigonometric inverse tangent, element-wise.

- ***np.hypot(x1, x2)***: Given the “legs” of a right triangle, return its hypotenuse.

- ***np.arctan2(x1, x2)***: Element-wise arc tangent of x1/x2 choosing the quadrant correctly.

- ***np.degrees(x)***: Convert angles from radians to degrees.

- ***np.radians(x)***: Convert angles from degrees to radians.

Now we will create a function that given an in x, it give an out $$sin ^ 2 (x) + cos ^ 2 (x)$$

In [22]:
def sin2cos2(x):
    return (np.sin(x)**2)+(np.cos(x)**2)

We know that $$sin ^ 2 (x) + cos ^ 2 (x) = 1 $$ $ \forall x $ So let's check it

In [23]:
for i in range(6):
    print(sin2cos2(i))

1.0
1.0
1.0
0.9999999999999999
1.0
0.9999999999999999


### 1.03 Statistical operations <a class="stat" id="stat"></a>

- ***np.amin()***: This function determines the minimum value of the element along a specified axis.
- ***np.amax()***: This function determines the maximum value of the element along a specified axis.
- ***np.mean()***: It determines the mean value of the data set.
- ***np.median()***: It determines the median value of the data set.
- ***np.std()***: It determines the standard deviation
- ***np.var()***: It determines the variance.
- ***np.cov()***: Estimate a covariance matrix, given data and weights.
- ***np.ptp()***: It returns a range of values along an axis.
- ***np.average()***: It determines the weighted average
- ***np.percentile()***: It determines the nth percentile of data along the specified axis.
- ***np.histogram(a[, bins, range, normed, weights, …])***: Compute the histogram of a dataset.

*For more NumPy commands for statistics functions*

https://numpy.org/doc/stable/reference/routines.statistics.html


### Hyperbolic functions <a class="hyp" id="hyp"></a>

- ***np.sinh(x)***: Hyperbolic sine, element-wise.

- ***np.cosh(x)***: Hyperbolic cosine, element-wise.

- ***np.tanh(x)***: Compute hyperbolic tangent element-wise.

- ***np.arcsinh(x)***: Inverse hyperbolic sine element-wise.

- ***np.arccosh(x)***:  Inverse hyperbolic cosine, element-wise.

- ***np.arctanh(x)***: Inverse hyperbolic tangent element-wise.

### Other functions <a class="other" id="other"></a>
- ***np.exp(x)***: Calculate the exponential of all elements in the input array.

- ***np.log(x)***: Natural logarithm, element-wise.

- ***np.log10(x)***: Return the base 10 logarithm of the input array, element-wise.

- ***np.sqrt(x)***: Return the non-negative square-root of an array, element-wise.

- ***np.square(x)***: Return the element-wise square of the input.

- ***np.absolute(x)***: Calculate the absolute value element-wise.

- ***np.maximum(x1, x2)***: Element-wise maximum of array elements.

- ***np.minimum(x1, x2)***: Element-wise minimum of array elements.
- ***np.diff(a)***: Calculate the n-th discrete difference along the given axis.
- ***np.gradient(f)***: Return the gradient of an N-dimensional array.

*For more NumPy commands for mathematical functions*

https://numpy.org/doc/stable/reference/routines.math.html

## 1.04 Bitwise operators <a class="bit" id="bit"></a>
In computer programming, a bitwise operation operates on a bit string, a bit array or a binary numeral (considered as a bit string) at the level of its individual bits. 
You can use bitwise operators to implement algorithms such as compression, encryption, error detection, and to perform Boolean logic on individual bits. 
<img src=https://miro.medium.com/max/540/1*lwKj-TpvToBxuq98LXII1A.png>
### Bitwise AND
It performs logical conjunction on the corresponding bits of its operands. For each pair of bits occupying the same position in the two numbers, it returns a one only when both bits are switched on. In all other places, at least one of the inputs has a zero bit. The resulting bit pattern is an intersection of the operator’s arguments.
<img src=https://files.realpython.com/media/and.ef7704d02d6f.gif>

### Bitwise OR
It performs logical disjunction. For each corresponding pair of bits, it returns a one if at least one of them is switched on. 
The resulting bit pattern is a union of the operator’s arguments. Only a combination of two zeros gives a zero in the final output.
<img src=https://files.realpython.com/media/or.7f09664e2d15.gif>

### Bitwise XOR
It evaluates two mutually exclusive conditions and tells you whether exactly one of them is met. The choice is mandatory.
It performs exclusive disjunction on the bit pairs, in other words, every bit pair must contain opposing bit values to produce a one.

<img src=https://files.realpython.com/media/xor.8c17776dd501.gif>

The bits switched on in the result where both numbers have different bit values. Bits in the remaining positions cancel out because they’re the same.

### Bitwise NOT
It expects just one argument, making it the only unary bitwise operator. It performs logical negation on a given number by flipping all of its bits.
The inverted bits are a complement to one, which turns zeros into ones and ones into zeros.

<img src=https://files.realpython.com/media/not.7edac5691829.gif>

### Left Shift
It moves the bits of its first operand to the left by the number of places specified in its second operand. It also insert enough zero bits to fill the gap that arises on the right edge of the new bit pattern.

<img src=https://files.realpython.com/media/lshift.e06f1509d89f.gif>

### Right Shift
It moves bits to the right by the specified number of places. The rightmost bits always get dropped.
<img src=https://files.realpython.com/media/rshift.9d585c1c838e.gif>

### Commands

- ***np.bitwise_and(x1, x2)***: Compute the bit-wise AND of two arrays element-wise.

- ***np.bitwise_or(x1, x2)***: Compute the bit-wise OR of two arrays element-wise.

- ***np.bitwise_xor(x1, x2)***: Compute the bit-wise XOR of two arrays element-wise.

- ***np.invert(x)***: Compute bit-wise inversion, or bit-wise NOT, element-wise.

- ***np.left_shift(x1, x2)***: Shift the bits of an integer to the left.

- ***np.right_shift(x1, x2)***: Shift the bits of an integer to the right.

*For more information go to:*

https://realpython.com/python-bitwise-operators/

https://numpy.org/doc/stable/reference/routines.bitwise.html

## 1.05 Copying & viewing arrays <a class="copy" id="copy"></a>
The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy. Making a copy takes more time.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

In [4]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(arr)
print(x)
print(y)

[1 2 3 4 5]
[1 2 3 4 5]
[1 2 3 4 5]


## 1.06 Stacking <a class="stack" id="stack"></a>
Stacking is the concept of joining arrays in NumPy. Arrays having the same dimensions can be stacked. The stacking is done along a new axis.

- ***vstack()***: it performs vertical stacking along the rows.
- ***hstack()***: it performs horizontal stacking along with the columns.
- ***dstack()***: it performs in-depth stacking along a new third axis.
- ***np.stack(array,axis)***
- ***np.column_stack()***:
- ***np.row_stack()***:

In [70]:
a = np.array([1, 2, 3])
b = np.array([4,5,6])
np.vstack((a,b)) # np.vstack((top,bottom))

array([[1, 2, 3],
       [4, 5, 6]])

You can also stack horizontally

In [67]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [68]:
np.dstack((a,b))

array([[[1, 4],
        [2, 5],
        [3, 6]]])

If you want delete the second row on each of your different arrays,

In [72]:
c = np.delete(a,1,0)
d = np.delete(b,1,0)
np.vstack((c,d))

array([[1, 3],
       [4, 6]])

To combine the arrays i'm going to call column stack

In [73]:
np.column_stack((c,c))

array([[1, 1],
       [3, 3]])

To change rows instead of columns

In [74]:
np.row_stack((c,c))

array([[1, 3],
       [1, 3]])

We use joining functions to append and concatenate elements and arrays.
- ***np.concatenate()***: join a sequence of arrays along an existing axis.
- ***np.append(arr, values, axis=None)***: it creates a new array along a specified axis, it creates a copy of the original array.

In [6]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7,8]])
a = np.concatenate((arr1, arr2))
print(a)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [7]:
b = np.append(arr1,arr2, axis=1)
print(b)

[[1 2 5 6]
 [3 4 7 8]]


## 1.07 Matrix Operations <a class="matrix" id="matrix"></a>
We can apply the commands that we already know to matrices.
- ***np.add()***: add elements of two matrices.
- ***np.subtract()***: subtract elements of two matrices.
- ***np.divide()***: divide elements of two matrices.
- ***np.multiply()***: multiply elements of two matrices.
- ***np.sqrt()***: square root of each element of matrix.

We also have specific commands for matrices
- ***np.inner(a,b)***: Inner product of two arrays.
- ***np.vdot(a, b)***: Return the dot product of two vectors.
- ***matmul(x1, x2)***: Matrix product of two arrays.
- ***tensordot(a, b)***: Compute tensor dot product along specified axes.
- ***np.sum(x,axis)***: add to all the elements in matrix. Second argument is optional, it is used when we want to compute the column sum if axis is 0 and row sum if axis is 1.
- ***np.transpose()***=***ndarray.T***: It performs transpose of the specified matrix.
- ***ndarray.trace()***: is the sum of diagonal elements in a square matrix.
- ***np.linalg.matrix_rank()***: is the dimensions of the vector space spanned (generated) by its columns or rows.
- ***np.linalg.det()***: it calculates the determinant of a square matrix.
- ***np.linalg.inv()***: It calculates the true inverse of a square matrix. If the determinant of a square matrix is not 0, it has a true inverse.
- ***ndarray.flatten***: is a simple method to transform a matrix into a one-dimensional numpy array.
### Eigenvalues and eigenvectors
Let A be an n x n matrix. A scalar λ is called an eigenvalue of A if there is a non-zero vector x satisfying the following equation.
$$A\bar{v}=\lambda \bar{v}$$
Where the vector $\bar{v}$ is called the eigenvector of A corresponding to $\lambda$.

- ***eigenvalues, eigenvectors = np.linalg.eig(array)***

*For more example about matrix operations:*

https://towardsdatascience.com/top-10-matrix-operations-in-numpy-with-examples-d761448cb7a8

## 1.08 Linear algebra <a class="linear" id="linear"></a>
- ***np.linalg.solve(a, b)***: Solve a linear matrix equation, or system of linear scalar equations.
- ***np.linalg.tensorsolve(a, b)***: Solve the tensor equation a x = b for x.
- ***np.linalg.lstsq(a, b)***: Return the least-squares solution to a linear matrix equation.
- ***np.linalg.inv(a)***: Compute the (multiplicative) inverse of a matrix.
- ***np.linalg.pinv(a)***: Compute the (Moore-Penrose) pseudo-inverse of a matrix.
- ***np.linalg.tensorinv(a)***: Compute the ‘inverse’ of an N-dimensional array.

*For more information*

https://numpy.org/doc/stable/reference/routines.linalg.html#solving-equations-and-inverting-matrices

In [111]:
from numpy import linalg as LA

We are going to use this arrays

In [97]:
arrA = np.array([[1,2], [3,4]])#5
arrB = np.array([[2,4], [6,9]])#6
arrC = np.array([[5,6], [7,8]])#8
print("arrA\n", arrA)
print("arrB\n", arrB)
print("arrC\n", arrC)

arrA
 [[1 2]
 [3 4]]
arrB
 [[2 4]
 [6 9]]
arrC
 [[5 6]
 [7 8]]


### Matrix multiplicaction with Dot product

<img src=https://hadrienj.github.io/assets/images/2.2/dot-product.png>

In [95]:
np.dot(arrA, arrB)

array([[14, 22],
       [30, 48]])

You can perform the dot product using more than two arrays.

In [98]:
LA.multi_dot([arrA, arrB, arrC])

array([[224, 260],
       [486, 564]])

### Inner product

In [99]:
np.inner(arrA,arrB)

array([[10, 24],
       [22, 54]])

In [ ]:
### Einstein summation

<img src=>

In [123]:
arrD = np.array([0,1])
arrE = np.array([[0,1,2,3],[4,5,6,7]])
print("arrD\n",arrD)
print("arrE\n", arrE)

arrD
 [0 1]
arrE
 [[0 1 2 3]
 [4 5 6 7]]


*i,ij*, says that we are going to be using one axis for arrD and two axis for arrE.

*->i*, we want a one dimesonal array

*j* It means that we want to multiply arrD and its individual single items by each column of array 12 and then you're going to sum those values

In [122]:
np.einsum('i,ij->i', arrD, arrE)

array([ 0, 22])

### Raise matrix to the power of n
$$\Rightarrow A^2=A\cdot A =\begin{pmatrix}
1 & 1 \\ 
1 & 1
\end{pmatrix}\cdot \begin{pmatrix}
1 & 1 \\ 
1 & 1
\end{pmatrix}=\begin{pmatrix}
2 & 2 \\ 
2 & 2
\end{pmatrix}$$

$$\Rightarrow A^3=A^2 \cdot A =\begin{pmatrix}
2 & 2 \\ 
2 & 2
\end{pmatrix}\cdot \begin{pmatrix}
1 & 1 \\ 
1 & 1
\end{pmatrix}=\begin{pmatrix}
4 & 4 \\ 
4 & 4
\end{pmatrix}$$

$$\Rightarrow A^4=A^3\cdot A =\begin{pmatrix}
4 & 4 \\ 
4 & 4
\end{pmatrix}\cdot \begin{pmatrix}
1 & 1 \\ 
1 & 1
\end{pmatrix}=\begin{pmatrix}
8 & 8 \\ 
8 & 8
\end{pmatrix}$$
$$\Rightarrow A^5=A^4\cdot A =\begin{pmatrix}
8 & 8 \\ 
8 & 8
\end{pmatrix}\cdot \begin{pmatrix}
1 & 1 \\ 
1 & 1
\end{pmatrix}=\begin{pmatrix}
16 & 16 \\ 
16 & 16
\end{pmatrix}$$

In [141]:
arrF = np.array([[1,1],[1,1]])
print('A^2=\n',LA.matrix_power(arrF,2))
print('A^3=\n',LA.matrix_power(arrF,3))
print('A^4=\n',LA.matrix_power(arrF,4))
print('A^5=\n',LA.matrix_power(arrF,5))

A^2=
 [[2 2]
 [2 2]]
A^3=
 [[4 4]
 [4 4]]
A^4=
 [[8 8]
 [8 8]]
A^5=
 [[16 16]
 [16 16]]


### Kronecker product of 2 arrays
$${\begin{bmatrix}1&2\\3&4\\\end{bmatrix}}\otimes {\begin{bmatrix}0&5\\6&7\\\end{bmatrix}}={\begin{bmatrix}1{\begin{bmatrix}0&5\\6&7\\\end{bmatrix}}&2{\begin{bmatrix}0&5\\6&7\\\end{bmatrix}}\\3{\begin{bmatrix}0&5\\6&7\\\end{bmatrix}}&4{\begin{bmatrix}0&5\\6&7\\\end{bmatrix}}\\\end{bmatrix}}={\begin{bmatrix}1\times 0&1\times 5&2\times 0&2\times 5\\1\times 6&1\times 7&2\times 6&2\times 7\\3\times 0&3\times 5&4\times 0&4\times 5\\3\times 6&3\times 7&4\times 6&4\times 7\\\end{bmatrix}}={\begin{bmatrix}0&5&0&10\\6&7&12&14\\0&15&0&20\\18&21&24&28\end{bmatrix}}$$

In [145]:
arrG = np.array([[1,2],[3,4]])
arrH = np.array([[0,5],[6,7]])
np.kron(arrG, arrH)

array([[ 0,  5,  0, 10],
       [ 6,  7, 12, 14],
       [ 0, 15,  0, 20],
       [18, 21, 24, 28]])

### Compute eigenvalues

In [133]:
LA.eig(arrA) #It returns eigenvectors 

(array([-0.37228132,  5.37228132]),
 array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [136]:
LA.eigvals(arrA) #It returns eigenvalues

array([-0.37228132,  5.37228132])

### Get vector norm 
$$\sqrt{\sum_i x_i^2}$$

In [138]:
LA.norm(arrA)

5.477225575051661

### Get multiplicative inverse of a matrix
$$A\times A^{-1}=1$$

In [139]:
LA.inv(arrA)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

### Get condition number of matrix

In [140]:
LA.cond(arrA)

14.933034373659265

### Determinant
$$ |A|={\begin{vmatrix}a_{11}&a_{12}\\a_{21}&a_{22}\end{vmatrix}}=a_{11}a_{22}-a_{12}a_{21}$$

In [154]:
LA.det(arrA)

-2.0000000000000004

### Solving system of linear equations
$$x+4y=10\\ 6x+18y=42$$
$$\Rightarrow x=-1, y=3$$

In [155]:
arrI = np.array([[1,4],[6,18]])
arrJ = np.array([10,42])
LA.solve(arrI,arrJ)

array([-2.,  3.])

## 1.11 Getting data in/out <a class="get" id="get"></a>
### CSV

In [90]:
from numpy import genfromtxt

In [92]:
filef =  genfromtxt('file_f.csv', delimiter=',')
filef = [row[~np.isnan(row)] for row in filef]
filef

[array([], dtype=float64),
 array([  0.        ,  -2.        , -10.56183478]),
 array([ 1.        , -1.93939394, -8.23185349]),
 array([ 2.        , -1.87878788, -9.53495274]),
 array([ 3.        , -1.81818182, -9.24133556]),
 array([  4.        ,  -1.75757576, -10.31981521]),
 array([ 5.        , -1.6969697 , -9.60997769]),
 array([  6.        ,  -1.63636364, -10.48117612]),
 array([ 7.        , -1.57575758, -9.42026318]),
 array([  8.        ,  -1.51515152, -12.78932796]),
 array([  9.        ,  -1.45454545, -10.77253635]),
 array([10.        , -1.39393939, -9.24333319]),
 array([11.        , -1.33333333, -9.93887381]),
 array([12.        , -1.27272727, -8.89555105]),
 array([13.        , -1.21212121, -9.56581476]),
 array([ 14.        ,  -1.15151515, -10.34616499]),
 array([15.        , -1.09090909, -9.19895736]),
 array([16.        , -1.03030303, -8.50204924]),
 array([17.        , -0.96969697, -7.55144059]),
 array([18.        , -0.90909091, -7.01061417]),
 array([ 19.        ,  -

### Homework
- Create a function that given an in x, it give an out $sec^2(x)-tan^2(x)$ and check that for different values it gives 1.